### ISSUE TITLE
authentication.run not firing when deployed to Azure

### ISSUE THREAD

**Issue by mattruma** [JamesRandall/react-azure-b2c#19]
I have deployed my app to Azure and for some reason the authentication.run is not firing. I can console.log the config settings, and everything looks OK. Just gives me a blank page. 

Anyone else run into this issue?

**Comment by justinlettau** [comment]
@mattruma did you resolve the issue? I seem to have encounted the same issue. For me, the issue seems to go away when I sign out of my Azure Microsoft account or use a different browser entirely (that's not signed into a Microsoft account).

**Comment by mattruma** [comment]
Hi @justinlettau ... what I ended up doing was just copying the code into a separate file ... couldn't get it working from the node_modules folder. 

Not ideal, but had a project that had to get done. 🙂

**Comment by justinlettau** [comment]
@mattruma Intresting. You copied the source code of this library into a file directly in your project? And it worked? I don't have this issue if I open my Azure hosted app in Incognito or a different browser ... not long term ideal.
